version: "3"
services:
  evanli-postgres:
    container_name: evanli-postgres
    image: library/postgres:14.5
    environment:
      POSTGRES_USER: evanliuser
      POSTGRES_PASSWORD: evanlipassword
      POSTGRES_DB: evanli
    networks:
      - backend
    ports:
      - 5432:5432

  users:
    container_name: evanli-users
    image: eshurupov/evanli-users:1.1
    depends_on:
      - evanli-postgres
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://evanli-postgres:5432/evanli
      SPRING_DATASOURCE_USERNAME: evanliuser
      SPRING_DATASOURCE_PASSWORD: evanlipassword
      LIQUIBASE_URL: jdbc:postgresql://evanli-postgres:5432/evanli
      LIQUIBASE_USER: evanliuser
      LIQUIBASE_PASSWORD: evanlipassword
      CUSTOM_SWAGGER_SERVER_URL: http://localhost
    ports:
      - 8001:8001

  wallets:
    container_name: evanli-wallets
    image: eshurupov/evanli-wallets:1.2
    depends_on:
      - evanli-postgres
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://evanli-postgres:5432/evanli
      SPRING_DATASOURCE_USERNAME: evanliuser
      SPRING_DATASOURCE_PASSWORD: evanlipassword
      LIQUIBASE_URL: jdbc:postgresql://evanli-postgres:5432/evanli
      LIQUIBASE_USER: evanliuser
      LIQUIBASE_PASSWORD: evanlipassword
      AUTH_SERVER: http://evanli-users:8001/api/profile
      CUSTOM_SWAGGER_SERVER_URL: http://localhost
    ports:
      - 8002:8002

  tasks:
    container_name: evanli-tasks
    image: eshurupov/evanli-tasks:1.0
    depends_on:
      - evanli-postgres
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://evanli-postgres:5432/evanli
      SPRING_DATASOURCE_USERNAME: evanliuser
      SPRING_DATASOURCE_PASSWORD: evanlipassword
      LIQUIBASE_URL: jdbc:postgresql://evanli-postgres:5432/evanli
      LIQUIBASE_USER: evanliuser
      LIQUIBASE_PASSWORD: evanlipassword
      AUTH_SERVER: http://evanli-users:8001/api/profile
      CUSTOM_SWAGGER_SERVER_URL: http://localhost
    ports:
      - 8003:8003

  balancer:
    container_name: evanli-balancer
    image: eshurupov/evanli-balancer:1.3
    depends_on:
      - users
      - wallets
      - tasks
    ports:
      - 80:80
    networks:
      - backend

networks:
  backend: