version: "3"
services:
  bp-postgres:
    container_name: bp-postgres-dev
    image: library/postgres:14.5
    environment:
      POSTGRES_USER: bpuser
      POSTGRES_PASSWORD: bppassword
      POSTGRES_DB: bp
    networks:
      - backend
    ports:
      - 5432:5432

  users:
    build:
      context: ./users
      dockerfile: ./DevDockerfile
    container_name: bp-users
    image: eshurupov/bp-users:dev
    depends_on:
      - bp-postgres
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bp-postgres:5432/bp
      SPRING_DATASOURCE_USERNAME: bpuser
      SPRING_DATASOURCE_PASSWORD: bppassword
      LIQUIBASE_URL: jdbc:postgresql://bp-postgres:5432/bp
      LIQUIBASE_USER: bpuser
      LIQUIBASE_PASSWORD: bppassword
    ports:
      - 8001:8001
      - 5001:5001
    volumes:
      - "./users/target:/opt/project"

  tasks:
    build:
      context: ./tasks
      dockerfile: ./DevDockerfile
    container_name: bp-tasks
    image: eshurupov/bp-tasks:dev
    depends_on:
      - bp-postgres
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bp-postgres:5432/bp
      SPRING_DATASOURCE_USERNAME: bpuser
      SPRING_DATASOURCE_PASSWORD: bppassword
      LIQUIBASE_URL: jdbc:postgresql://bp-postgres:5432/bp
      LIQUIBASE_USER: bpuser
      LIQUIBASE_PASSWORD: bppassword
      AUTH_SERVER: http://users:8001/api/profile
    ports:
      - 8002:8002
      - 5002:5002
    volumes:
      - "./tasks/target:/opt/project"

  ui:
    container_name: bp-ui
    image: eshurupov/bp-ui:1.0
    ports:
      - 9000:9000
    networks:
      - backend

  balancer:
    container_name: bp-balancer
    image: eshurupov/bp-balancer:1.2
    depends_on:
      - users
      - tasks
    ports:
      - 80:80
    networks:
      - backend

networks:
  backend: