server:
  port: 8001

jwt:
  expirationMs: 76300000
  secret: knowledgeFactory

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bp
    username: bpuser
    password: bppassword
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

liquibase:
  enabled: true
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/bp
  user: bpuser
  password: bppassword

springdoc:
  api-docs.path: /users/api-docs
  swagger-ui:
    urls:
      - name: users
        url: /users/api-docs
        display-name: Пользователи и аутентификация
      - name: tasks
        url: /tasks/api-docs
        display-name: Задания