---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bp-users
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bp-users
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bp-users
    spec:
      containers:
        - image: eshurupov/bp-users:1.1
          name: bp-users
          ports:
            - containerPort: 8001
          env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: bpconfig
                  key: jwt_secret
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: bpconfig
                  key: bp_db_jdbcurl
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: bpconfig
                  key: bp_db_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bpconfig
                  key: bp_db_password
            - name: LIQUIBASE_URL
              valueFrom:
                configMapKeyRef:
                  name: bpconfig
                  key: bp_db_jdbcurl
            - name: LIQUIBASE_USER
              valueFrom:
                configMapKeyRef:
                  name: bpconfig
                  key: bp_db_username
            - name: LIQUIBASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bpconfig
                  key: bp_db_password
            - name: CUSTOM_SWAGGER_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: bpconfig
                  key: bp_host



---
apiVersion: v1
kind: Service
metadata:
  name: bp-users
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8001
  selector:
    app: bp-users
  type: ClusterIP
