---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evanli-wallets
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evanli-wallets
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: evanli-wallets
    spec:
      containers:
        - image: eshurupov/evanli-wallets:1.2
          name: evanli-wallets
          ports:
            - containerPort: 8002
          env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: evanliconfig
                  key: jwt_secret
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: evanliconfig
                  key: evanli_db_jdbcurl
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: evanliconfig
                  key: evanli_db_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: evanliconfig
                  key: evanli_db_password
            - name: LIQUIBASE_URL
              valueFrom:
                configMapKeyRef:
                  name: evanliconfig
                  key: evanli_db_jdbcurl
            - name: LIQUIBASE_USER
              valueFrom:
                configMapKeyRef:
                  name: evanliconfig
                  key: evanli_db_username
            - name: LIQUIBASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: evanliconfig
                  key: evanli_db_password
            - name: CUSTOM_SWAGGER_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: evanliconfig
                  key: evanli_host
            - name: AUTH_SERVER
              value: http://evanli-users.default.svc.cluster.local/api/profile



---
apiVersion: v1
kind: Service
metadata:
  name: evanli-wallets
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8002
  selector:
    app: evanli-wallets
  type: ClusterIP
